### PR TITLE
add i18n methods to untranslatble strings in block

### PR DESCRIPTION
**Pull request by cherbst**

### CODE REVIEW

**Comment by igmoweb** [comment]
Merging! Thanks a lot for your contribution. I will release a new version today.

**Comment by cherbst** [comment]
Thank you @igmoweb for merging this PR but it seems the changes have not yet made it into the new release. Could this be? I still do not get all translated strings in my installation.

**Comment by igmoweb** [comment]
@cherbst Sorry for the late reply here. I've just pushed a new plugin version in WordPress.org, I think it should work, could you tell me if it works for you? Thanks!

**Comment by cherbst** [comment]
Yes it works! Thank you very much!

**Pull request merged**
